[package]

name = "treeoflife_optimizer"
version = "0.0.1"
authors = ["Chris Horne <lahwran@lahwran.net>",
            "Melanie Heisey <mheisey.nox@gmail.com"]

[dependencies]
chrono = "0.2.1"
rand = "0.1.3"

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
